### ISSUE TITLE
Use all 3 timer outputs for a timer

### ISSUE THREAD

**Issue by QuadCorei8085** [dadul96/Arduino-Servo-Hardware-PWM-Library#4]
Wanted to use your library but noticed you are using the wrong WGM mode.

Using WGM mode 14 (FastPWM with IRCn as TOP) you can use all 3 timer outputs and no need to define the TOP value by sacraficing the ORCnA.

This works:

    TCCR3A = (2 << COM3A0) | (2 << COM3B0) | (2 << COM3C0) | (1 << WGM31) | (0 << WGM30);
    TCCR3B = (1 << WGM33) | (0 << WGM32) | (2 << CS30);
    TCCR3C = 0;

    ICR3 = 20000;

    OCR3A = 1000;
    OCR3B = 1500;
    OCR3C = 2000;

    DDRE |= (1 << PE3) | (1 << PE4) | (1 << PE5);

**Comment by dadul96** [comment]
There is actually a reason why I chose WGM mode 15 over mode 14 (see [datasheet](http://ww1.microchip.com/downloads/en/DeviceDoc/Atmel-2549-8-bit-AVR-Microcontroller-ATmega640-1280-1281-2560-2561_datasheet.pdf) pp. 147-148):

> The procedure for updating ICRn differs from updating OCRnA when used for defining the TOP value. The ICRn Register is not double buffered. This means that if ICRn is changed to a low value when the counter is running with none or a low prescaler value, there is a risk that the new ICRn value written is lower than the current value of TCNTn. The result will then be that the counter will miss the compare match at the TOP value. The counter will then have to count to the MAX value (0xFFFF) and wrap around starting at 0x0000 before the compare match can occur. The OCRnA Register however, is double buffered. This feature allows the OCRnA I/O location to be written anytime. When the OCRnA I/O location is written the value written will be put into the OCRnA Buffer Register. The OCRnA Compare Register will then be updated with the value in the Buffer Register at the next timer clock cycle the TCNTn matches TOP. The update is done at the same timer clock cycle as the TCNTn is cleared and the TOVn Flag is set. 
Using the ICRn Register for defining TOP works well when using fixed TOP values. By using ICRn, the OCRnA Register is free to be used for generating a PWM output on OCnA. However, if the base PWM frequency is actively changed (by changing the TOP value), using the OCRnA as TOP is clearly a better choice due to its double buffer feature.

Due to the fact that I needed a highly reliable servo-motion the WGM mode 15 was chosen, but I think this would be a good idea for a new feature. There the user could decide whether he wants to use the "reliable mode" or 3 more output pins (pin 5, 6, 46).

And I think that you have a mistake in your proposed code. In my opinion, the value of `WGM32` should be set to `1` instead of `0`, but please correct me if I am wrong.

**Comment by QuadCorei8085** [comment]
Yes that WGM32 should be set one to reflect WGM mode 14.

What do you mean "highly reliable"? The quoted paragraph says that when changing ICRn you might have a problem, timer might reach MAX and the next TOP value will be adapted with the cycle. This register is reponsible generating the period. The duty that matters is still coming from the double buffered OCRnm registers.

If ICRn is set once (during init) it will work fine - at least for those servos that I have worked with do not require changing the period.

**Comment by dadul96** [comment]
Looks like I had a thinking error when selecting the WGM mode. Of course, you're right, because the ICRn is only responsible for the period and not for the duty-cycle, as I mistakenly assumed.

Thank you very much, for pointing out my error! I will implement the correct solution as soon as possible. For sure I will mention you in the acknowledgments for your help. :thumbsup:
